forcing the eventType to be PageAction. If you use the directives of …
angulartics/angulartics-newrelic-insights pull request #3
Opened 2017-03-29 20:14 UTC by danenone

…angulartics on href the eventType will be click. New Relic is not accept that as valid.

2017-03-30 09:01 UTC, gampleman approved these changes

2017-03-30 12:43 UTC, gampleman requested changes

2017-03-30 12:43 UTC, gampleman commented on lib/angulartics-newrelic-insights.js
> +          properties.eventType = 'PageAction';
On further reflection, mutating an object that we don't own seems like a bad idea.

2017-03-30 13:15 UTC, danenone commented on lib/angulartics-newrelic-insights.js
> +          properties.eventType = 'PageAction';
I don't disagree with you at all. Here is the issue. I have a element <a class="btn btn-sm btn-warning"
                                   analytics-on
                                   analytics-event="itemAddedToCart-productView"
                                   analytics-category="cart"
                                   analytics-label={{productCtrl.product.id}}
                                   ng-click="productCtrl.adjustCartQuantity(productCtrl.product)"
                                   ng-if="productCtrl.showAddToCartButton()">

this sends an eventType of "click" to new relic. New Relic responses with a 400 Bad Request. Do you have another suggestion for me to look at? or would it be better for me to change a few values ie if eventType === 'click' then eventType = 'PageAction' so we are deliberate in how the object is modified?

2017-03-30 14:06 UTC, gampleman commented on lib/angulartics-newrelic-insights.js
> +          properties.eventType = 'PageAction';
I think the solution would be to clone the object before it gets mutated, so something like:

```javascript
$analyticsProvider.registerEventTrack(function(action, properties) {
   var propertiesCopy = angular.copy(properties);
   propertiesCopy.eventType = 'PageAction';
   newrelic.addPageAction(action, properties);
});
```

Also if you could add a link as a comment to some documentation that explains why this is necessary, that would be great.

2017-03-30 15:58 UTC, danenone commented on lib/angulartics-newrelic-insights.js
> +          properties.eventType = 'PageAction';
I will make the changes. I am contacting new relic to see if I can get some official documentation about it.

2017-04-03 13:28 UTC, danenone commented
I have not heard back on the documentation from our new relic rep yet.

2017-04-05 16:15 UTC, danenone commented
@gampleman I think I have made all the changes you requested.

2017-04-06 07:53 UTC, gampleman approved these changes

2017-04-06 07:55 UTC, merged